### ISSUE TITLE
Extended syntax highlighting support

### ISSUE THREAD

**Issue by valdar-hu** [vimtaai/gumdrop#9]
**Limitation**
Gumdrop uses Prism for syntax highlighting in the latest (4.1.5) version with the default language support which contains only the following languages: 
- Markup (markup, html, xml, svg, mathml)  
- CSS (css)
- C-like (clike)
- JavaScript (javascript, js)

There are many use cases when the user want to highlight different languages, for example: Java, SQL and now that is not supported.

**Solution**
There is an [autoloader](https://prismjs.com/plugins/autoloader/) plugin for Prism. 
If somebody integrate this plugin into gumdrop it will be able to load and highlight all the used languages automatically.

**Comment by bucsi** [comment]
Most people use Gumdrop with (the ELTE-flavored) [MDSS](https://github.com/vimtaai/mdss), and that combination cannot use Prism. I think MDSS and Prism compatibility should be a higher priority than more syntax highlight options.

**Comment by vimtaai** [comment]
@bucsi This is more of an issue with the mdss package.

**Comment by valdar-hu** [comment]
@bucsi - You can use ELTE-flavored MDSS with Gumdrop and Prism. You just need to include the prism.css

**Comment by vimtaai** [comment]
Added in 4.2.0

**Comment by valdar-hu** [comment]
It works like a charm with the 4.2.1 version. Thank you :)
